openapi: 3.0.3
info:
  title: Minecraft Clipboard Sync API
  version: 1.1.0

servers:
  - url: /api

paths:
  /clipboard/copy:
    post:
      summary: Save clipboard data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [data]
              properties:
                data:
                  type: string
                  description: Base64-encoded clipboard data
                description:
                  type: string
                  description: Optional description
      responses:
        '200':
          description: Data saved
        '403':
          description: IP not allowed

  /clipboard/paste:
    post:
      summary: Get latest clipboard data
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: Optional specific entry ID to fetch
      responses:
        '200':
          description: Clipboard data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: integer }
                  date: { type: string }
                  description: { type: string }
                  data: { type: string }
        '403':
          description: IP not allowed
        '500':
          description: Error with explanation

  /clipboard/list:
    get:
      summary: List all clipboard entries for the authenticated user
      responses:
        '200':
          description: List of entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        date: { type: string }
                        description: { type: string }
        '403':
          description: IP not allowed
        '500':
          description: Error with explanation

  /reload:
    post:
      summary: Reload configuration
      responses:
        '200':
          description: Config reloaded
        '403':
          description: IP not allowed
